import {
  attribute,
  table,
  autoGeneratedHashKey,
} from '@aws/dynamodb-data-mapper-annotations';

@table(process.env.TRANSACTION_TABLE)
export class Transaction {
  @autoGeneratedHashKey()
  id: string;

  @attribute()
  artWorkId: string;

  @attribute()
  transactionHash: string;

  @attribute()
  transactionState?: string;
}
